remove subscription after SIGTERM called
sonnythehottest/pubtail pull request #3
Opened 2018-04-10 10:19 UTC by ryosagisu

fix #3

2018-04-10 10:26 UTC, sonnythehottest commented
pls put reference to issue on the description

2018-04-10 10:26 UTC, ryosagisu commented
fix #3

2018-04-11 04:42 UTC, smanurung requested changes

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +	c := make(chan os.Signal, 2)
Agree we'll need buffered channel for this (to avoid the risk to miss signal when the receiver is not ready yet). But I think buffer channel with buffer size `1` will be enough. IMHO.

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
Is `CTRL + C` releasing `SIGINT` signal? If it's, how's it handled?

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
Oh I just read this - https://golang.org/pkg/os/#Signal. It said that `os.Interrupt` is actually `SIGINT`. :+1:

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +		<-c
On receiving signal, pls print some logs, e.g. `log.Infoln("receiving signal: %s - will exit gracefully", s)`.

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +				fmt.Println(err)
pls use standardized `log.Errorf()` or `log.Errorln()`

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +			fmt.Println("Subscription deleted.")
If we want to print each of subscriptions deleted, we need to
1. use standard `log.Info()`
2. give context of the name of topic/subscription which is just deleted

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +		fmt.Println("cleaned")
pls use standard logging too here

2018-04-11 04:42 UTC, sonnythehottest commented on pubtail.go
> +		os.Exit(0)
why do we call `Exit()` here?

2018-05-01 04:52 UTC, smanurung requested changes
overall OK - need to some changes of log formatting

2018-05-01 04:52 UTC, sonnythehottest commented on pubtail.go
> +		log.Infoln("receiving signal: %s - will exit gracefully", s)
for passing param - we need to use `log.Infof()`

2018-05-01 04:52 UTC, sonnythehottest commented on pubtail.go
> +				log.Errorln(err)
I think we should return after printing the error, not continue printing `Subscription x has beed deleted`

2018-06-11 06:36 UTC, smanurung approved these changes

2018-07-16 03:43 UTC, merged